# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeddingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeddingApp
  pod 'ExpyTableView'
  pod 'iOSDropDown'

  target 'WeddingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeddingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
